<template>
  <div class="content-wrapper">
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>Point of contact List</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Our Employee</a></li>
              <li class="breadcrumb-item active">Point of contact</li>
            </ol>
          </div>
        </div>
      </div>
      <!-- /.container-fluid -->
    </section>
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-12">
            <div class="input-group mb-3 col-md-4">
              <input
                type="text"
                class="form-control"
                placeholder="search"
                aria-label="search"
                aria-describedby="basic-addon2"
                v-model="search"
              />
              <div class="input-group-append">
                <button
                  class="btn btn-secondary"
                  @click="getResults"
                  type="button"
                >
                  Search
                </button>
              </div>
            </div>
            <div class="card">
              <div class="card-header">
                <h3 class="card-title">Point of Contact</h3>
                <div class="card-tools">
                  <button
                    type="button"
                    class="btn btn-default d-none d-sm-block"
                    @click="newModal"
                  >
                    New POC <i class="fas fa-user-plus"></i>
                  </button>
                </div>
              </div>
              <!-- /.card-header -->
              <div class="card-body p-0">
                <div class="table-responsive">
                  <table class="table">
                    <thead>
                      <tr>
                        <th>#</th>
                        <th style="min-width: 180px">Pont Of Contact Name</th>
                        <th style="min-width: 180px">Pont Of Contact No.</th>
                        <th style="min-width: 180px">Atlantic User</th>
                        <th style="min-width: 180px">Atlantic Username</th>
                        <th style="min-width: 180px">Resaller Company Name</th>
                        <th style="min-width: 180px">Sales Person Name</th>
                        <th style="min-width: 180px">Lead Generated By</th>
                        <th style="min-width: 180px">Date</th>
                        <th>Action</th>
                      </tr>
                    </thead>
                    <tbody>
                      <tr
                        v-for="contact in PontOfContactList.data"
                        :key="contact.id"
                      >
                        <td>{{ contact.id }}</td>
                        <td>{{ contact.poc_name }}</td>
                        <td>
                          <p>{{ contact.poc_contact_no }}</p>
                        </td>
                        <td>{{ contact.atlantic_user.name }}</td>
                        <td>{{ contact.atlantic_user.username }}</td>
                        <td>{{ contact.reseller_company_name }}</td>
                        <td>{{ contact.sales_person_name }}</td>
                        <td>{{ contact.lead_generated_by }}</td>
                        <td>{{ contact.created_at }}</td>
                        <td>
                          <div
                            class="btn-group"
                            role="group"
                            aria-label="Basic example"
                          >
                            <button
                              type="button"
                              class="btn btn-secondary btn-sm"
                              @click="editModal(contact)"
                            >
                              <i class="fas fa-user-edit"></i>
                            </button>
                          </div>
                        </td>
                      </tr>
                      <tr v-show="!PontOfContactList.data.length">
                        <td colspan="5">No data found</td>
                      </tr>
                    </tbody>
                  </table>
                </div>
              </div>
              <div class="overlay" v-if="isLoad">
                <i class="fas fa-2x fa-sync-alt fa-spin"></i>
              </div>
              <div class="card-footer clearfix">
                <pagination
                  :data="PontOfContactList"
                  @pagination-change-page="getResults"
                  :limit="8"
                  :show-disabled="true"
                >
                  <template #prev-nav>
                    <span>&lt; Previous</span>
                  </template>
                  <template #next-nav>
                    <span>Next &gt;</span>
                  </template>
                </pagination>
              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->
          </div>
        </div>
        <div
          class="modal fade bd-example-modal-lg"
          tabindex="-1"
          role="dialog"
          aria-labelledby="myLargeModalLabel"
          aria-hidden="true"
          id="newModal"
        >
          <div class="modal-dialog modal-lg">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">New message</h5>
                <button
                  type="button"
                  class="close"
                  data-dismiss="modal"
                  aria-label="Close"
                >
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body">
                <div class="row">
                  <div class="col-md-4">
                    <div class="form-group">
                      <label for="tmpos_id">Atlantic User:</label>
                      <!-- <multiselect
                        v-model="searchValue"
                        :options="ownerList"
                        :custom-label="nameWithLang"
                        placeholder="Select atlantic user"
                        label="name"
                        track-by="tmpos_id"
                        @select="onSelect"
                      ></multiselect> -->

                      <div
                        class="text-danger"
                        v-if="form.errors.has('tmpos_id')"
                        v-html="form.errors.get('tmpos_id')"
                      />
                    </div>
                  </div>
                  <div class="col-md-4">
                    <div class="form-group">
                      <label for="poc_name">Point Of Contact Name:</label>
                      <input
                        v-model="form.poc_name"
                        type="text"
                        name="poc_name"
                        placeholder=""
                        class="form-control"
                        :class="{ 'is-invalid': form.errors.has('poc_name') }"
                      />

                      <div
                        class="text-danger"
                        v-if="form.errors.has('poc_name')"
                        v-html="form.errors.get('poc_name')"
                      />
                    </div>
                  </div>
                  <div class="col-md-4">
                    <div class="form-group">
                      <label for="poc_contact_no">Point Of Contact No:</label>
                      <input
                        v-model="form.poc_contact_no"
                        type="text"
                        name="poc_contact_no"
                        placeholder=""
                        class="form-control"
                        :class="{
                          'is-invalid': form.errors.has('poc_contact_no'),
                        }"
                      />

                      <div
                        class="text-danger"
                        v-if="form.errors.has('poc_contact_no')"
                        v-html="form.errors.get('poc_contact_no')"
                      />
                    </div>
                  </div>
                </div>
                <div class="row">
                  <div class="col-md-4">
                    <div class="form-group">
                      <label for="poc_alternate_contact_no"
                        >POC Alternative Contact No:</label
                      >
                      <input
                        v-model="form.poc_alternate_contact_no"
                        type="text"
                        name="poc_alternate_contact_no"
                        placeholder=""
                        class="form-control"
                        :class="{
                          'is-invalid': form.errors.has(
                            'poc_alternate_contact_no'
                          ),
                        }"
                      />

                      <div
                        class="text-danger"
                        v-if="form.errors.has('poc_alternate_contact_no')"
                        v-html="form.errors.get('poc_alternate_contact_no')"
                      />
                    </div>
                  </div>
                  <div class="col-md-4">
                    <div class="form-group">
                      <label for="poc_company_mail_id"
                        >Point Of Contact Company Email:</label
                      >
                      <input
                        v-model="form.poc_company_mail_id"
                        type="text"
                        name="poc_company_mail_id"
                        placeholder=""
                        class="form-control"
                        :class="{
                          'is-invalid': form.errors.has('poc_company_mail_id'),
                        }"
                      />

                      <div
                        class="text-danger"
                        v-if="form.errors.has('poc_company_mail_id')"
                        v-html="form.errors.get('poc_company_mail_id')"
                      />
                    </div>
                  </div>
                  <div class="col-md-4">
                    <div class="form-group">
                      <label for="poc_address">Point Of Contact Address:</label>
                      <textarea
                        v-model="form.poc_address"
                        type="text"
                        name="poc_address"
                        placeholder=""
                        class="form-control"
                        :class="{
                          'is-invalid': form.errors.has('poc_address'),
                        }"
                      ></textarea>

                      <div
                        class="text-danger"
                        v-if="form.errors.has('poc_address')"
                        v-html="form.errors.get('poc_address')"
                      />
                    </div>
                  </div>
                </div>

                <div class="row">
                  <div class="col-md-4">
                    <div class="form-group">
                      <label for="reseller_company_name"
                        >Reseller Company Name:</label
                      >
                      <input
                        v-model="form.reseller_company_name"
                        type="text"
                        name="reseller_company_name"
                        placeholder=""
                        class="form-control"
                        :class="{
                          'is-invalid': form.errors.has(
                            'reseller_company_name'
                          ),
                        }"
                      />

                      <div
                        class="text-danger"
                        v-if="form.errors.has('reseller_company_name')"
                        v-html="form.errors.get('reseller_company_name')"
                      />
                    </div>
                  </div>
                  <div class="col-md-4">
                    <div class="form-group">
                      <label for="reseller_company_mail_id"
                        >Reseller Company Email:</label
                      >
                      <input
                        v-model="form.reseller_company_mail_id"
                        type="text"
                        name="reseller_company_mail_id"
                        placeholder=""
                        class="form-control"
                        :class="{
                          'is-invalid': form.errors.has(
                            'reseller_company_mail_id'
                          ),
                        }"
                      />

                      <div
                        class="text-danger"
                        v-if="form.errors.has('reseller_company_mail_id')"
                        v-html="form.errors.get('reseller_company_mail_id')"
                      />
                    </div>
                  </div>
                  <div class="col-md-4">
                    <div class="form-group">
                      <label for="reseller_company_address"
                        >Reseller Company Address:</label
                      >
                      <textarea
                        v-model="form.reseller_company_address"
                        type="text"
                        name="reseller_company_address"
                        placeholder=""
                        class="form-control"
                        :class="{
                          'is-invalid': form.errors.has(
                            'reseller_company_address'
                          ),
                        }"
                      ></textarea>

                      <div
                        class="text-danger"
                        v-if="form.errors.has('reseller_company_address')"
                        v-html="form.errors.get('reseller_company_address')"
                      />
                    </div>
                  </div>
                </div>

                <div class="row">
                  <div class="col-md-4">
                    <div class="form-group">
                      <label for="sales_person_name">Sales Person Name:</label>
                      <input
                        v-model="form.sales_person_name"
                        type="text"
                        name="sales_person_name"
                        placeholder=""
                        class="form-control"
                        :class="{
                          'is-invalid': form.errors.has('sales_person_name'),
                        }"
                      />

                      <div
                        class="text-danger"
                        v-if="form.errors.has('sales_person_name')"
                        v-html="form.errors.get('sales_person_name')"
                      />
                    </div>
                  </div>
                  <div class="col-md-4">
                    <div class="form-group">
                      <label for="sales_person_mail_id"
                        >Sales Person Email:</label
                      >
                      <input
                        v-model="form.sales_person_mail_id"
                        type="text"
                        name="sales_person_mail_id"
                        placeholder=""
                        class="form-control"
                        :class="{
                          'is-invalid': form.errors.has('sales_person_mail_id'),
                        }"
                      />

                      <div
                        class="text-danger"
                        v-if="form.errors.has('sales_person_mail_id')"
                        v-html="form.errors.get('sales_person_mail_id')"
                      />
                    </div>
                  </div>
                  <div class="col-md-4">
                    <div class="form-group">
                      <label for="sales_person_address"
                        >Sales Person Address:</label
                      >
                      <textarea
                        v-model="form.sales_person_address"
                        type="text"
                        name="sales_person_address"
                        placeholder=""
                        class="form-control"
                        :class="{
                          'is-invalid': form.errors.has('sales_person_address'),
                        }"
                      ></textarea>

                      <div
                        class="text-danger"
                        v-if="form.errors.has('sales_person_address')"
                        v-html="form.errors.get('sales_person_address')"
                      />
                    </div>
                  </div>
                </div>

                <div class="row">
                  <div class="col-md-4">
                    <div class="form-group">
                      <label for="lead_generated_by">Lead Generated By:</label>
                      <input
                        v-model="form.lead_generated_by"
                        type="text"
                        name="lead_generated_by"
                        placeholder=""
                        class="form-control"
                        :class="{
                          'is-invalid': form.errors.has('lead_generated_by'),
                        }"
                      />

                      <div
                        class="text-danger"
                        v-if="form.errors.has('lead_generated_by')"
                        v-html="form.errors.get('lead_generated_by')"
                      />
                    </div>
                  </div>
                  <div class="col-md-4">
                    <div class="form-group">
                      <label for="lead_generatedby_contactno"
                        >Lead Generatedby Contact no:</label
                      >
                      <input
                        v-model="form.lead_generatedby_contactno"
                        type="text"
                        name="lead_generatedby_contactno"
                        placeholder=""
                        class="form-control"
                        :class="{
                          'is-invalid': form.errors.has(
                            'lead_generatedby_contactno'
                          ),
                        }"
                      />

                      <div
                        class="text-danger"
                        v-if="form.errors.has('lead_generatedby_contactno')"
                        v-html="form.errors.get('lead_generatedby_contactno')"
                      />
                    </div>
                  </div>
                  <div class="col-md-4">
                    <div class="form-group">
                      <label for="lead_generatedby_address"
                        >Lead Generated by address:</label
                      >
                      <textarea
                        v-model="form.lead_generatedby_address"
                        type="text"
                        name="lead_generatedby_address"
                        placeholder=""
                        class="form-control"
                        :class="{
                          'is-invalid': form.errors.has(
                            'lead_generatedby_address'
                          ),
                        }"
                      ></textarea>

                      <div
                        class="text-danger"
                        v-if="form.errors.has('lead_generatedby_address')"
                        v-html="form.errors.get('lead_generatedby_address')"
                      />
                    </div>
                  </div>
                  <div class="col-md-4">
                    <div class="form-group">
                      <label for="lead_generatedby_mail"
                        >Lead Generated by mail:</label
                      >
                      <input
                        v-model="form.lead_generatedby_mail"
                        type="text"
                        name="lead_generatedby_mail"
                        placeholder=""
                        class="form-control"
                        :class="{
                          'is-invalid': form.errors.has(
                            'lead_generatedby_mail'
                          ),
                        }"
                      />

                      <div
                        class="text-danger"
                        v-if="form.errors.has('lead_generatedby_mail')"
                        v-html="form.errors.get('lead_generatedby_mail')"
                      />
                    </div>
                  </div>
                </div>
              </div>
              <div class="modal-footer">
                <button
                  class="btn btn-primary"
                  v-if="editmode"
                  @click="update()"
                >
                  Update
                </button>
                <button
                  class="btn btn-primary"
                  v-if="!editmode"
                  @click="create()"
                >
                  Create
                </button>
                <button class="btn btn-danger" @click="cancel()">Cancel</button>
              </div>
            </div>
          </div>
        </div>
      </div>
      <!-- /.container-fluid -->
    </section>
  </div>
</template>
<style src="vue-multiselect/dist/vue-multiselect.min.css"></style>
<script>
import Form from "vform";
import LaravelVuePagination from "laravel-vue-pagination";
import Multiselect from "vue-multiselect";
export default {
  components: {
    Multiselect,
    pagination: LaravelVuePagination,
  },
  data() {
    return {
      // users empty array
      editmode: false,
      PontOfContactList: { data: [] },
      searchValue: "",
      ownerList: [],
      page: 1,
      isLoad: false,
      form: new Form({
        id: null,
        tmpos_id: "",
        poc_name: "",
        poc_contact_no: "",
        poc_address: "",
        poc_company_mail_id: "",
        poc_alternate_contact_no: "",
        reseller_company_name: "",
        reseller_company_mail_id: "",
        reseller_company_address: "",
        sales_person_name: "",
        sales_person_address: "",
        sales_person_mail_id: "",
        lead_generated_by: "",
        lead_generatedby_contactno: "",
        lead_generatedby_mail: "",
        lead_generatedby_address: "",
      }),
      search: "",
    };
  },
  methods: {
    // Our method to GET results from a Laravel endpoint
    getResults(page = 1) {
      this.page = page;
      this.isLoad = true;
      // point-of-contact
      axios
        .get("api/point-of-contact?q=" + this.search + "&page=" + page)
        .then((response) => {
          this.isLoad = false;
          //   console.log(response.data);
          this.PontOfContactList = response.data;
        });
    },
    newModal() {
      this.editmode = false;
      this.searchValue = "";
      this.form.reset();
      this.$refs["newModal"].show();
    },
    editModal(x) {
      console.log(x);
      this.searchValue = x.atlantic_user;
      this.editmode = true;
      this.form.fill(x);

      this.$refs["newModal"].show();
    },
    cancel() {
      this.$refs["newModal"].hide();
    },
    update() {
      this.$Progress.start();
      this.form
        .post("api/point-of-contact/" + this.form.id)
        .then(() => {
          this.$refs["newModal"].hide();
          this.getResults();

          Swal.fire("Success", "Info has been updated !", "success");
          this.$Progress.finish();
        })
        .catch(() => {
          this.$Progress.fail();
        });
    },
    create() {
      this.$Progress.start();
      this.form
        .post("api/point-of-contact")
        .then(() => {
          this.$refs["newModal"].hide();
          this.getResults();

          Swal.fire("Success", "Info has been saved !", "success");
          this.$Progress.finish();
        })
        .catch(() => {
          this.$Progress.fail();
        });
    },
    getOwnerList() {
      axios.get("api/tmpos-users?all=1").then((response) => {
        this.ownerList = response.data;
      });
    },
    nameWithLang({ name }) {
      return `${name}`;
    },

    onSelect(option) {
      this.form.tmpos_id = option.tmpos_id;
    },
  },
  mounted() {
    this.getResults();
    this.getOwnerList();
  },
};
</script>
